# Compiler definitions
# OS Name        : Linux 
# OS Architecture: Linux arch: x86_64
# Debug Mode     : off
CC_EXE=g++
CC_FLAGS_EXE=-DVERSION=\"1.8.3\" -D_GNU_SOURCE -D_REENTRANT -Wall -fPIC -Werror -DINIT_CALL_FILTER
LD_EXE=g++
LD_FLAGS_EXE=-rdynamic
LD_LIBS_EXE=-lpthread -lfl -ldl
LEX_EXE=flex
LEX_FLAGS_EXE=-l
LEX_CC_FLAGS_EXE=
YACC_EXE=bison
YACC_FLAGS_EXE=-y -d
YACC_CC_FLAGS_EXE=

CC_LIB=g++
CC_FLAGS_LIB=-D_GNU_SOURCE -D_REENTRANT -shared -Wall -fPIC -Werror
LD_LIB=g++
LD_FLAGS_LIB=-shared -fPIC
LD_LIBS_LIB=-lpthread
LEX_LIB=
LEX_FLAGS_LIB=
LEX_CC_FLAGS_LIB=
YACC_LIB=
YACC_FLAGS_LIB=
YACC_CC_FLAGS_LIB=

CC_SIMPLE_EXE=gcc
CC_FLAGS_SIMPLE_EXE=-Wall -fPIC -Werror
LD_SIMPLE_EXE=gcc
LD_FLAGS_SIMPLE_EXE=
LD_LIBS_SIMPLE_EXE=
LEX_SIMPLE_EXE=
LEX_FLAGS_SIMPLE_EXE=
LEX_CC_FLAGS_SIMPLE_EXE=
YACC_SIMPLE_EXE=
YACC_FLAGS_SIMPLE_EXE=
YACC_CC_FLAGS_SIMPLE_EXE=

